- README.md
- build.sbt
- docker/Dockerfile
- src/main/scala/com/socrata/geocodingsecondary/GeocodingHandler.scala
- src/main/scala/com/socrata/geocodingsecondary/GeocodingSecondary.scala
- src/test/scala/com.socrata.geocodingsecondary/GeocodingHandlerTest.scala
- src/test/scala/com.socrata.geocodingsecondary/TestData.scala
- version.sbt
* adds optional parameters to `parameters` in the
computation strategy.
* a default value will be used in the case that
the corresponding column does not exist or the
value for a row is null.
* also updates to latest version of secondary-watcher
> EN-4817: Support default values in comp. strategy

- build.sbt
- docker/Dockerfile
New `secondarylib-feedback` version
has fix for adding to the cookie
correctly during `Secondary.version(.)`.
> EN-7507: Use fixed library version

- build.sbt
New `secondarylib-feedback` version
has fix for actually throwing a resync
exception when a new computed column
of matching strategy type is added
during `Secondary.version(.)`
> EN-7507: Resync when comp col is added

- build.sbt
Because we're still _building_ with Java 7, even though we're _deploying_
on Java 8.
> ..and now downgrade typesafe-config

- build.sbt
- src/main/resources/secondary-manifest.json
* URL encode strings sent to MapQuest
* Also remove unused `secondary-manifest.json` file
> EN-8588: Use fixed version of `geocoders`

- src/main/scala/com/socrata/geocodingsecondary/RegionCodingHandler.scala
For consistency with our other wrapped-string types.
Also correctness.
Sort of.
> Serialize resource names as themselves

- build.sbt
- docker/secondary.conf.j2
- src/main/resources/reference.conf
- src/main/scala/com/socrata/geocodingsecondary/GeocodingSecondary.scala
- src/test/scala/com.socrata.geocodingsecondary/TestData.scala
Update to new version of `secondarylib-feedback`
library that implements this new functionality.
> EN-6889: Use export calls to DC instead of resync

- build.sbt
- src/main/scala/com/socrata/geocodingsecondary/GeocodingHandler.scala
- src/test/scala/com.socrata.geocodingsecondary/TestData.scala
* As better handling of MapQuest returning the
wrong number of results.
* Url encodes addresses for MapQuest (EN-8588)
> EN-8946: Update to new `geocoders` version

- build.sbt
* Only URL encode `%` symbolds for MapQuest
* Actually handle their non-HTTP status codes
> EN-9429: Update to fixed `geocoders` library

- docker/ship.d/run
With Java 8, we need to add this flag to handle OutOfMemoryErrors the way we want to. Otherwise the worker threads will crash but the main thread won't.
> EN-6995: handle OutOfMemoryErrors gracefully

- build.sbt
Use new secondaryLib library version with:
- retry logic for releasing claims
- in memory "working set" of  claimed datasets
to prevent from re-claiming a dataset
whose claim we failed to release
- health check on claim update happening
on desired interval
> EN-4585: Improved secondary-watcher claims

- build.sbt
Main changes:
* secondary-watcher updates version on the secondary manifest
in a new transaction.
Other changes:
* restrict resync datasets of the same secondary group to happen
one at a time. Since geocoding-secondary is not part of a group
this shouldn't change resync behavior for the secondary.
Refs EN-13224
This depends on migration in truth to create the resync table.
568cc622e645772311af84cf7204e7dbbebc7319
> EN-13225: Bump secondary-watcher version

- build.sbt
Fix regression where `secondary_manifest.retry_num`
is not incremented when there is an error in resync.
The fix is in the secondary-watcher library code.
> EN-13224: Fix regression where resync never breaks

- build.sbt
Avoid deadlocks when updating multiple rows on the
`secondary_manifest` by first obtaining locks on
the rows in a deterministic order, i.e. ordery by
`dataset_system_id` then `store_id`.
> EN-12729: Avoid deadlocks with new SW lib version

- src/main/scala/com/socrata/geocodingsecondary/RegionCodingHandler.scala
Don't attempt to access the source column key when it
may not exist for a given row.
> EN-17085: Fix bug with region coding null points

- docker/secondary.conf.j2
- src/main/scala/com/socrata/geocodingsecondary/RegionCodingHandler.scala
Properly log the job-id and dataset-id during the parallel
region coding calls and send that job-id to region coder
so we can actually correlate logs.
Remove unused log4j config from docker file.
This is for debugging failed region coding.
> EN-17842: Better logging during region-coding call

- build.sbt
Support geocoded computed columns without source columns.
Bring in new version of feedback library to allow this.
> EN-7442: Support no source columns for geocoding

- build.sbt
- src/test/scala/com.socrata.geocodingsecondary/TestData.scala
WARNING: changes require downtime for service!!!!
Bring in new library version of feebback-secondary library
that always upserts to data-coordinator using the system id
column. This is to avoid a bug reading the user primary key
values in data-coordinator responses as the wrong type.
Depends on data-coordinator running with changes in commit
0bd6a77dc9c64f960a3e2fa580e6569c2b0a3c65
And the migration in 2c58c73e4abb6bc50f0f91bd53da350be8f0f896
having been run on truth. Geocoding-secondary will have to be
stopped before the migration and then started on this new version
after the migration has been run.
> EN-19241: Geocoding-secondary does not use user PK

- build.sbt
Bring in fixed feedback secondary library version with a bug
fix for datasets with user primary key columns. Always
export the system id column from data-coordinator since it
is not automatically returned for datasets with user pks.
> EN-19241: Bug fix for datasets with user PK column

- README.md
- build.sbt
- configs/application-alpha.conf
- configs/application-bravo.conf
- configs/application-charlie.conf
- configs/sample-geocoding-secondary.conf
- docker/Dockerfile
- docker/secondary-watcher.conf.j2
Bump data-coordinatory library version to inlcude collocation work and
make needed config file additions. So we don't have to deal with this
later when pulling in needed SecondaryWatcher / FeedbackSecondary
library changes.
Also, update README's run instructions to refer to the local
checked-in configuration file `configs/application.conf`.
(See EN-21594)
> EN-21895: Bump DC version to include collocation

- .gitignore
- README.md
- configs/application.conf
- configs/sample.conf
Clearly comment that it was for solo (becaus I was confused).
Also, a little bit of config renaming to match spandex based
off of code reviews there.
Note: still need to actually setup solo for this service.
> EN-22044: Explicit use of local.dev.socrata.net

- src/main/scala/com/socrata/geocodingsecondary/RegionCodingHandler.scala
There's a corresponding commit in region-coder to understand this.
> EN-40040: Send the job id _as_ the job ID, not request ID

- Jenkinsfile
This commit changes the build and release process to make it work with the current process:
* The image tag is in the default format for all builds `${serviceVersion}_${buildNumber}_${gitSHA.take(8)}`
* The release tag is added to the commit where the version is bumped by another process
* The release builds will be triggered on a schedule by another job
* The release builds checkout the closest tag to the head of main and build on it
> EN-66034: fix release build

- Jenkinsfile
- build.sbt
This commit updates the pipelines library version and makes the necessary changes to the parameters to adopt sbtWrappter instead of sbtBuild.
> EN-77317: update pipelines version
